services:
    train:
        build:
            context: .
            dockerfile: model-train/Dockerfile.train
        volumes:
            - mnist:/opt/mount/model
            - data:/opt/mount/data

    evaluate:
        build:
            context: .
            dockerfile: model-eval/Dockerfile.eval
        volumes:
            - mnist:/opt/mount/model
            - data:/opt/mount/data

    infer:
        build:
            context: .
            dockerfile: model-infer/Dockerfile.infer
        volumes:
            - mnist:/opt/mount/model
            - data:/opt/mount/data

volumes:
  mnist:
  data:
