services:
    train:
        build:
            context: .
            dockerfile: model-train/Dockerfile.train
        volumes:
            - mnist:/opt/mount

    evaluate:
        build:
            context: .
            dockerfile: model-eval/Dockerfile.eval
        volumes:
            - mnist:/opt/mount

    infer:
        build:
            context: .
            dockerfile: model-infer/Dockerfile.infer
        volumes:
            - mnist:/opt/mount

volumes:
  mnist:
