FROM shravankgl/elmo4-tsai:session2

WORKDIR /workdir

COPY model.py /workdir/
COPY model-train/train.py /workdir/

CMD ["python", "train.py", "--epochs", "1", "--num-processes", "2", "--save-dir", "/opt/mount"]